name: E2E Playwright (Chromium) + Build Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:focal
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build extension .zip
        run: npm run build:zip

      - name: Install Playwright browsers & deps
        run: npx playwright install --with-deps

      - name: Run Playwright tests (headless)
        run: npm run test:e2e:ci

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload extension ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: dist/extension.zip
